source "https://rubygems.org"

gem 'github-pages', group: :jekyll_plugins
# gem "autoprefixer-rails"
# gem "html-proofer"
# gem "image_optim"
gem "jekyll"
# gem "jekyll-assets"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jemoji"
# gem "mini_magick"
gem "sass"
# gem "sprockets", "~> 3.7"
# gem "uglifier"